name: SmallRye Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/checkout@v4
        name: checkout

      - uses: actions/setup-java@v4
        name: set up jdk ${{matrix.java}}
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'

      - name: build with maven
        run: mvn -B formatter:validate verify --file pom.xml

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        java: [17, 21]
    name: build with jdk ${{matrix.java}} windows

    steps:
      - uses: actions/checkout@v4
        name: checkout

      - uses: actions/setup-java@v4
        name: set up jdk ${{matrix.java}}
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'

      - name: build with maven
        run: mvn -B formatter:validate verify --file pom.xml
